#!/usr/bin/env bash
# claude-shim install script.
#
# Sets up a Python venv, an /etc/claude-shim.env config, and a systemd unit
# for the shim. Idempotent — re-running just refreshes the venv and re-links
# the unit. Run as root (it writes /etc/ + /opt/ paths).

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/claude-shim}"
ENV_FILE="${ENV_FILE:-/etc/claude-shim.env}"
SERVICE_USER="${SERVICE_USER:-${SUDO_USER:-$USER}}"
UNIT_PATH="/etc/systemd/system/claude-shim.service"

if [[ $EUID -ne 0 ]]; then
  echo "Re-run with sudo so the systemd unit can be installed." >&2
  exit 1
fi

# Resolve the source dir of this script — the repo's tools/claude-shim/.
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "[1/5] Creating ${INSTALL_DIR} owned by ${SERVICE_USER} ..."
mkdir -p "${INSTALL_DIR}"
cp "${SRC_DIR}/shim.py" "${INSTALL_DIR}/shim.py"
chown -R "${SERVICE_USER}:${SERVICE_USER}" "${INSTALL_DIR}"

echo "[2/5] Building venv at ${INSTALL_DIR}/venv ..."
sudo -u "${SERVICE_USER}" python3 -m venv "${INSTALL_DIR}/venv"
sudo -u "${SERVICE_USER}" "${INSTALL_DIR}/venv/bin/pip" install --quiet --upgrade pip
sudo -u "${SERVICE_USER}" "${INSTALL_DIR}/venv/bin/pip" install --quiet fastapi uvicorn pydantic

echo "[3/5] Seeding ${ENV_FILE} (only if absent) ..."
if [[ ! -f "${ENV_FILE}" ]]; then
  TOKEN="$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | base64 | tr -d '+/=' | head -c 32)"
  cat > "${ENV_FILE}" <<EOF
# Generated by tools/claude-shim/install.sh. Edit values, then:
#   sudo systemctl restart claude-shim

SHIM_BIND_HOST=0.0.0.0
SHIM_BIND_PORT=8090

# Mandatory in production. Anyone with this token can use the operator's
# Claude Code subscription, so treat it like a password.
SHIM_BEARER_TOKEN=${TOKEN}

# Comma-separated IP allow-list. Empty = allow all. Set this to the LAN
# IPs of the services calling the shim (e.g. your Pi).
SHIM_ALLOW_IPS=

# Override only if claude isn't on root's PATH (or the service user's PATH).
# Use an absolute path here when in doubt — systemd does not source ~/.bashrc.
SHIM_CLAUDE_BIN=claude

# Empty = Claude Code default. Set e.g. claude-haiku-4-5 to pin the model.
SHIM_CLAUDE_MODEL=

# Defence in depth.
SHIM_MAX_PROMPT_BYTES=32768
SHIM_TIMEOUT_SECONDS=60
EOF
  chmod 600 "${ENV_FILE}"
  chown "${SERVICE_USER}:${SERVICE_USER}" "${ENV_FILE}"
  echo "    Wrote ${ENV_FILE} with a freshly generated bearer token."
else
  echo "    ${ENV_FILE} already exists — not overwriting."
fi

echo "[4/5] Installing systemd unit ${UNIT_PATH} ..."
cp "${SRC_DIR}/claude-shim.service" "${UNIT_PATH}"
# Patch the User= and paths in the unit if the install dir / user differs from the defaults.
sed -i "s|^User=.*|User=${SERVICE_USER}|" "${UNIT_PATH}"
sed -i "s|^EnvironmentFile=.*|EnvironmentFile=${ENV_FILE}|" "${UNIT_PATH}"
sed -i "s|^WorkingDirectory=.*|WorkingDirectory=${INSTALL_DIR}|" "${UNIT_PATH}"
sed -i "s|^ExecStart=.*|ExecStart=${INSTALL_DIR}/venv/bin/python ${INSTALL_DIR}/shim.py|" "${UNIT_PATH}"

systemctl daemon-reload
systemctl enable claude-shim.service >/dev/null

echo "[5/5] Done. Next steps:"
echo "  1. As ${SERVICE_USER}, run:   claude setup-token"
echo "     (Interactive — provisions a long-lived auth token in ~/.claude/.)"
echo "  2. Edit ${ENV_FILE} if you need to tweak port / allow-list / model."
echo "  3. sudo systemctl start claude-shim"
echo "  4. curl http://localhost:8090/health"
